required = [
  "github.com/vektra/mockery/cmd/mockery"
]

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2"

[prune]
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package = "github.com/tommy351/diiig/cmd/diiig-server"
  install = ["./cmd/..."]
